# Some More Numpy Functions - Statistics
- min, max
- mean 
- median
- average
- variance
- standard devidation

In [3]:
import numpy as np

In [5]:
# min and max
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))
#Specify axis for the direction in case of multidim array
print(np.min(a,axis=0))  #min from every column  
print(np.min(a,axis=1))  #min from every row

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [6]:
b = np.array([1,2,3,4,5])
m = sum(b)/5      #user defined method
print(m)
print(np.mean(b))  #in-built function.

print(np.mean(a,axis=0))  #mean of every column
print(np.mean(a,axis=1))  #mean of every row

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [35]:
# Mean vs Average is Weighted
c = np.array([1,5,4,2,0])    #in-build method
print(np.mean(c))

# Weights 
w = np.array([1,2,3,4,5])
print(np.average(c,weights=w))
w = np.array([1,1,1,1,1])
print(np.average(c,weights=w))

2.4
2.066666666666667
2.4


### median: 

In [36]:
c = np.array([1,5,4,2,0,5])    
print(np.median(c))         #in-build method

n=len(c)          # user-defined method(not used though)
c.sort()
if(n%2==0):
    median = ( c[n//2 - 1]+c[n//2] ) / 2
else:
    median = float(c[n//2])
print(median)

3.0
3.0


### Mode:

In [37]:
from scipy import stats
m = stats.mode(c)
print(m)

ModeResult(mode=array([5]), count=array([2]))


### Standard Deviation and Variance:


In [38]:
#Standard Deviation
dev= np.std(c)   #In built
print(dev)

#Variance
print(np.var(c))    #in built
                                                

# Standard Deviation
u = np.mean(c)  #mu is mean of array
myStd = np.sqrt(np.mean((c-u)**2))  # c-u is a array where all elements of c subtract mean from them
print(myStd)

#Variance = deviation**2
print(myStd**2)

1.9507833184532708
3.8055555555555554
1.9507833184532708
3.8055555555555554


In [42]:
arr = np.array([1,2,3,4,5])
arr = (arr + 5)**2    # this cannot be done in python lists. This is only possible in numpy array.
print(arr)

[ 36  49  64  81 100]
